# Generated by Django 6.1.1 on 2026-09-16 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='timeline/')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampilan')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
                'db_table': 'timelines',
                'ordering': ['urutan', 'tanggal'],
            },
        ),
    ]
