# Generated by Django 6.1.1 on 2026-09-16 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['urutan', 'created_at'], 'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
        migrations.AddField(
            model_name='timeline',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timeline',
            name='gambar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='timeline',
            name='icon',
            field=models.CharField(blank=True, default='Sparkles', max_length=50),
        ),
        migrations.AddField(
            model_name='timeline',
            name='kategori',
            field=models.CharField(blank=True, default='Pencapaian', max_length=100),
        ),
        migrations.AddField(
            model_name='timeline',
            name='tahun',
            field=models.CharField(blank=True, default='', help_text='Tahun milestone', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='tanggal',
            field=models.CharField(help_text='Label tanggal seperti "Maret 2024"', max_length=100),
        ),
    ]
