# Generated by Django 6.1.1 on 2026-09-16 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KomunitasActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, default='')),
                ('tipe', models.CharField(choices=[('event', 'Event'), ('workshop', 'Workshop'), ('pelatihan', 'Pelatihan'), ('pertemuan', 'Pertemuan')], default='event', max_length=20)),
                ('tanggal_mulai', models.DateTimeField(blank=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, default='', max_length=255)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='komunitas/activities/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aktivitas Komunitas',
                'verbose_name_plural': 'Aktivitas Komunitas',
                'db_table': 'komunitas_activities',
                'ordering': ['-tanggal_mulai', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KomunitasMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alasan_bergabung', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_komunitas_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='komunitas_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anggota Komunitas',
                'verbose_name_plural': 'Anggota Komunitas',
                'db_table': 'komunitas_members',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KomunitasTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('peran', models.CharField(blank=True, default='Anggota Komunitas', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='komunitas/testimonials/')),
                ('konten', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial Komunitas',
                'verbose_name_plural': 'Testimonial Komunitas',
                'db_table': 'komunitas_testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
