# Generated by Django 6.1.1 on 2026-09-16 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komunitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komunitas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(help_text='Deskripsi singkat')),
                ('deskripsi_lengkap', models.TextField(blank=True, default='', help_text='Deskripsi detail')),
                ('kategori', models.CharField(default='Organisasi Tuli', max_length=100)),
                ('platform', models.CharField(default='Website', max_length=50)),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='komunitas/logos/')),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('anggota', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('kontak', models.CharField(blank=True, default='', max_length=100)),
                ('email_kontak', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Direktori Komunitas',
                'verbose_name_plural': 'Direktori Komunitas',
                'db_table': 'komunitas_direktori',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='komunitastestimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonial'},
        ),
        migrations.AddField(
            model_name='komunitastestimonial',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='komunitastestimonial',
            name='peran',
            field=models.CharField(blank=True, default='Pengguna SETARA', max_length=255),
        ),
    ]
