# Generated by Django 6.1.1 on 2026-09-16 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipe_translasi', models.CharField(choices=[('text_to_sign', 'Text to Sign'), ('sign_to_text', 'Sign to Text')], max_length=20)),
                ('tipe_bahasa', models.CharField(choices=[('SIBI', 'SIBI'), ('BISINDO', 'BISINDO')], max_length=10)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True, default='')),
                ('video_ids', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation History',
                'verbose_name_plural': 'Translation Histories',
                'db_table': 'translation_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
