# Generated by Django 6.1.1 on 2026-09-16 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kata', models.CharField(db_index=True, help_text='Kata yang diwakili', max_length=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/isyarat/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video/thumbnails/')),
                ('tipe_bahasa', models.CharField(choices=[('SIBI', 'SIBI'), ('BISINDO', 'BISINDO')], default='SIBI', max_length=10)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('durasi', models.PositiveIntegerField(default=0, help_text='Durasi video dalam detik')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['kata'],
                'indexes': [models.Index(fields=['kata', 'tipe_bahasa'], name='videos_kata_126a3f_idx')],
            },
        ),
    ]
