# Generated by Django 6.1.1 on 2026-09-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='deskripsi_gerakan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='gesture_pattern',
            field=models.CharField(blank=True, default='hand_wave_forehead', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='kategori',
            field=models.CharField(blank=True, default='Umum', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='durasi',
            field=models.PositiveIntegerField(default=2, help_text='Durasi video dalam detik'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tipe_bahasa',
            field=models.CharField(choices=[('SIBI', 'SIBI'), ('BISINDO', 'BISINDO')], default='BISINDO', max_length=10),
        ),
    ]
