--
-- PostgreSQL database dump
--

\restrict Y7URCDMo7pb9wjCZ1SK5HutmLY2qivaOL8ThNfJTOtjHhHdcjzEm9FmWMjyjAnA

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-09-20 19:30:12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 33428)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 33427)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 33438)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 33437)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 33418)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 33417)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 33568)
-- Name: berita; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.berita (
    id uuid NOT NULL,
    judul character varying(255) NOT NULL,
    slug character varying(300) NOT NULL,
    konten text NOT NULL,
    kategori character varying(50) NOT NULL,
    thumbnail character varying(100),
    status character varying(20) NOT NULL,
    views integer NOT NULL,
    is_deleted boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    published_at timestamp with time zone,
    author_id uuid,
    author_name character varying(255) NOT NULL,
    ringkasan text NOT NULL,
    thumbnail_url character varying(500) NOT NULL,
    waktu_baca character varying(50) NOT NULL,
    CONSTRAINT berita_views_check CHECK ((views >= 0))
);


ALTER TABLE public.berita OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 33542)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 33541)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 33406)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 33405)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 33394)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33393)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 33658)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 33596)
-- Name: komunitas_activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.komunitas_activities (
    id uuid NOT NULL,
    judul character varying(255) NOT NULL,
    deskripsi text NOT NULL,
    tipe character varying(20) NOT NULL,
    tanggal_mulai timestamp with time zone,
    tanggal_selesai timestamp with time zone,
    lokasi character varying(255) NOT NULL,
    gambar character varying(100),
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.komunitas_activities OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 41598)
-- Name: komunitas_direktori; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.komunitas_direktori (
    id uuid NOT NULL,
    nama character varying(255) NOT NULL,
    deskripsi text NOT NULL,
    deskripsi_lengkap text NOT NULL,
    kategori character varying(100) NOT NULL,
    platform character varying(50) NOT NULL,
    link character varying(500) NOT NULL,
    logo character varying(100),
    logo_url character varying(500) NOT NULL,
    anggota character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    kontak character varying(100) NOT NULL,
    email_kontak character varying(254) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.komunitas_direktori OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 33611)
-- Name: komunitas_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.komunitas_members (
    id uuid NOT NULL,
    alasan_bergabung text NOT NULL,
    status character varying(20) NOT NULL,
    approved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    approved_by_id uuid,
    user_id uuid NOT NULL
);


ALTER TABLE public.komunitas_members OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 33626)
-- Name: komunitas_testimonials; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.komunitas_testimonials (
    id uuid NOT NULL,
    nama character varying(255) NOT NULL,
    peran character varying(255) NOT NULL,
    avatar character varying(100),
    konten text NOT NULL,
    rating integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id uuid,
    avatar_url character varying(500) NOT NULL
);


ALTER TABLE public.komunitas_testimonials OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 33670)
-- Name: timelines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.timelines (
    id uuid NOT NULL,
    judul character varying(255) NOT NULL,
    deskripsi text NOT NULL,
    tanggal character varying(100) NOT NULL,
    gambar character varying(100),
    urutan integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    gambar_url character varying(500) NOT NULL,
    icon character varying(50) NOT NULL,
    kategori character varying(100) NOT NULL,
    tahun character varying(20) NOT NULL,
    CONSTRAINT timelines_urutan_check CHECK ((urutan >= 0))
);


ALTER TABLE public.timelines OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 33684)
-- Name: translation_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.translation_history (
    id uuid NOT NULL,
    tipe_translasi character varying(20) NOT NULL,
    tipe_bahasa character varying(10) NOT NULL,
    input_text text NOT NULL,
    output_text text NOT NULL,
    video_ids jsonb NOT NULL,
    confidence_score double precision NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id uuid
);


ALTER TABLE public.translation_history OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 33474)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    avatar character varying(100),
    role character varying(20) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    bio text NOT NULL,
    is_komunitas_member boolean NOT NULL,
    joined_komunitas_at timestamp with time zone,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 33495)
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 33494)
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 33504)
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 33503)
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 33705)
-- Name: videos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.videos (
    id uuid NOT NULL,
    kata character varying(100) NOT NULL,
    video_file character varying(100),
    thumbnail character varying(100),
    tipe_bahasa character varying(10) NOT NULL,
    tag character varying(100) NOT NULL,
    durasi integer NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    deskripsi_gerakan text NOT NULL,
    gesture_pattern character varying(100) NOT NULL,
    kategori character varying(100) NOT NULL,
    thumbnail_url character varying(500) NOT NULL,
    video_url character varying(500) NOT NULL,
    CONSTRAINT videos_durasi_check CHECK ((durasi >= 0))
);


ALTER TABLE public.videos OWNER TO postgres;

--
-- TOC entry 5178 (class 0 OID 33428)
-- Dependencies: 226
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5180 (class 0 OID 33438)
-- Dependencies: 228
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5176 (class 0 OID 33418)
-- Dependencies: 224
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add User	6	add_user
22	Can change User	6	change_user
23	Can delete User	6	delete_user
24	Can view User	6	view_user
25	Can add Berita	7	add_berita
26	Can change Berita	7	change_berita
27	Can delete Berita	7	delete_berita
28	Can view Berita	7	view_berita
29	Can add Video	8	add_video
30	Can change Video	8	change_video
31	Can delete Video	8	delete_video
32	Can view Video	8	view_video
33	Can add Translation History	9	add_translationhistory
34	Can change Translation History	9	change_translationhistory
35	Can delete Translation History	9	delete_translationhistory
36	Can view Translation History	9	view_translationhistory
37	Can add Timeline	10	add_timeline
38	Can change Timeline	10	change_timeline
39	Can delete Timeline	10	delete_timeline
40	Can view Timeline	10	view_timeline
41	Can add Aktivitas Komunitas	11	add_komunitasactivity
42	Can change Aktivitas Komunitas	11	change_komunitasactivity
43	Can delete Aktivitas Komunitas	11	delete_komunitasactivity
44	Can view Aktivitas Komunitas	11	view_komunitasactivity
45	Can add Anggota Komunitas	12	add_komunitasmember
46	Can change Anggota Komunitas	12	change_komunitasmember
47	Can delete Anggota Komunitas	12	delete_komunitasmember
48	Can view Anggota Komunitas	12	view_komunitasmember
49	Can add Testimonial Komunitas	13	add_komunitastestimonial
50	Can change Testimonial Komunitas	13	change_komunitastestimonial
51	Can delete Testimonial Komunitas	13	delete_komunitastestimonial
52	Can view Testimonial Komunitas	13	view_komunitastestimonial
53	Can add Direktori Komunitas	14	add_komunitas
54	Can change Direktori Komunitas	14	change_komunitas
55	Can delete Direktori Komunitas	14	delete_komunitas
56	Can view Direktori Komunitas	14	view_komunitas
\.


--
-- TOC entry 5188 (class 0 OID 33568)
-- Dependencies: 236
-- Data for Name: berita; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.berita (id, judul, slug, konten, kategori, thumbnail, status, views, is_deleted, created_at, updated_at, published_at, author_id, author_name, ringkasan, thumbnail_url, waktu_baca) FROM stdin;
b05a2cd8-7a00-48f7-9488-b6e68f9f15e3	Peluncuran Platform SETARA untuk Teman Tuli	peluncuran-platform-setara-untuk-teman-tuli	<p>Platform SETARA resmi diluncurkan untuk memfasilitasi komunikasi inklusif.</p>	teknologi		published	0	f	2026-09-17 02:26:01.306308+07	2026-09-17 02:26:01.306319+07	2026-09-17 02:26:01.300481+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Tim Redaksi SETARA			4 menit
b14b36ac-4987-4922-a523-54ab944b1359	Fitur Baru Penerjemah SETARA v2	fitur-baru-penerjemah-setara-v2	<p>Platform SETARA resmi diluncurkan untuk memfasilitasi komunikasi inklusif.</p>	teknologi		published	1	f	2026-09-17 02:27:14.240234+07	2026-09-17 02:27:14.240251+07	2026-09-17 02:27:14.232236+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Tim Redaksi SETARA			4 menit
ba95c09d-25ca-46b3-b9ea-8211746f76ca	Penerapan YOLO 11 dan AI dalam Menjembatani Komunikasi Komunitas Tuli di Indonesia	revolusi-ai-yolo11-penerjemah-bahasa-isyarat-indonesia	Perkembangan kecerdasan buatan (AI) di bidang computer vision kini membuka babak baru bagi aksesibilitas digital di Indonesia. Dengan hadirnya model terbaru YOLO 11 Pose Estimation, deteksi titik sendi tangan (hand keypoints) dapat dilakukan hingga 21 titik per tangan secara presisi tanpa memerlukan perangkat keras khusus.\n\nDalam platform SETARA, teknologi ini dipadukan dengan sequence classifier (LSTM) untuk mengenali rangkaian gestur dinamis dan mengonversinya menjadi teks bahasa Indonesia seketika. Hal ini memungkinkan teman Tuli berkomunikasi dua arah secara natural di ruang publik, layanan kesehatan, maupun perkantoran.	Teknologi		published	1420	f	2026-09-17 03:26:37.073791+07	2026-09-17 03:26:37.073808+07	2026-09-17 03:26:37.066221+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Tim Litbang SETARA	Bagaimana teknologi Computer Vision dan pose estimation 21 titik kini mampu mengenali bahasa isyarat SIBI dan BISINDO secara real-time dengan latensi rendah.	https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80	4 menit
01e484b4-a410-4d4e-8e2c-171bb8c57b7f	Memahami Perbedaan Mendasar SIBI dan BISINDO: Panduan Lengkap untuk Pemula	memahami-perbedaan-mendasar-sibi-dan-bisindo	Seringkali masyarakat awam mengira bahwa bahasa isyarat di seluruh Indonesia adalah seragam. Kenyataannya, terdapat dua sistem utama: SIBI (Sistem Isyarat Bahasa Indonesia) dan BISINDO (Bahasa Isyarat Indonesia).\n\nSIBI diciptakan dengan mengacu pada tata bahasa baku Indonesia termasuk struktur afiksasi (imbuhan), sementara BISINDO adalah bahasa visual alami yang lahir dari budaya komunitas Tuli sendiri. Menghargai keduanya adalah kunci utama dalam membangun ekosistem masyarakat yang inklusif dan ramah disabilitas.	Edukasi		published	2890	f	2026-09-17 03:26:37.078794+07	2026-09-17 03:26:37.078809+07	2026-09-17 03:26:37.077242+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Nabila Saraswati (Edukator Isyarat)	Kenali latar belakang, filosofi, struktur linguistik, dan konteks penggunaan antara SIBI dan BISINDO agar tidak salah kaprah saat berinteraksi.	https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=80	6 menit
7e30ad08-6a06-4038-8cd8-b169010b7ed8	Festival Bahasa Isyarat Nasional 2026: Merayakan Keberagaman Budaya Tuli	festival-bahasa-isyarat-nasional-2026	Festival Bahasa Isyarat Nasional tahun ini menyuguhkan berbagai lokakarya interaktif, pertunjukan puisi isyarat (sign poetry), pameran teknologi inklusif, dan kompetisi penerjemah bahasa isyarat muda.\n\nAcara ini menegaskan komitmen bersama bahwa akses komunikasi yang setara adalah hak asasi setiap warga negara tanpa terkecuali.	Event		published	980	f	2026-09-17 03:26:37.081527+07	2026-09-17 03:26:37.081543+07	2026-09-17 03:26:37.079869+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Divisi Komunitas SETARA	Ribuan pegiat inklusivitas dan anggota komunitas Tuli dari berbagai provinsi berkumpul merayakan Hari Bahasa Isyarat Internasional.	https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80	3 menit
72da60d4-4e22-4503-94ba-e3752778ee2f	Inisiatif '1000 Kata Isyarat': Mendorong Sekolah Inklusif Sejak Usia Dini	gerakan-1000-kata-isyarat-di-sekolah-inklusif	Pendidikan inklusif tidak hanya tentang menerima siswa berkebutuhan khusus di sekolah umum, melainkan juga membekali teman-teman sebayanya dengan kemampuan berkomunikasi dasar.\n\nMelalui modul digital SETARA, para siswa diajak belajar kata-kata sapaan seperti Halo, Terima Kasih, Tolong, dan Semangat dengan cara interaktif dan menyenangkan.	Komunitas		published	1650	f	2026-09-17 03:26:37.084433+07	2026-09-17 03:26:37.084446+07	2026-09-17 03:26:37.082882+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Budi Santoso, S.Pd.	Program pengenalan kosa kata isyarat dasar pada murid sekolah dasar guna memupuk empati dan pemahaman inklusivitas sejak dini.	https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80	5 menit
f9e64f0a-ecee-4813-bc65-e7ff5955e25f	event seminar setara	event-seminar-setara	edukasi bahasa isyarat sibi dan bisindo, dan pelatihan bahasa isyarat sibi dan bisindo	Edukasi		published	0	f	2026-09-17 23:48:58.577804+07	2026-09-17 23:48:58.578305+07	2026-09-17 23:48:58.559152+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	Tim Redaksi SETARA	seminar setara yang ingin belajar lebih lanjut sibi dan bisindo		4 menit
\.


--
-- TOC entry 5187 (class 0 OID 33542)
-- Dependencies: 235
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5174 (class 0 OID 33406)
-- Dependencies: 222
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	berita	berita
8	video	video
9	translator	translationhistory
10	timeline	timeline
11	komunitas	komunitasactivity
12	komunitas	komunitasmember
13	komunitas	komunitastestimonial
14	komunitas	komunitas
\.


--
-- TOC entry 5172 (class 0 OID 33394)
-- Dependencies: 220
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-17 02:24:25.740232+07
2	contenttypes	0002_remove_content_type_name	2026-09-17 02:24:25.752522+07
3	auth	0001_initial	2026-09-17 02:24:25.818062+07
4	auth	0002_alter_permission_name_max_length	2026-09-17 02:24:25.825658+07
5	auth	0003_alter_user_email_max_length	2026-09-17 02:24:25.831739+07
6	auth	0004_alter_user_username_opts	2026-09-17 02:24:25.839068+07
7	auth	0005_alter_user_last_login_null	2026-09-17 02:24:25.845526+07
8	auth	0006_require_contenttypes_0002	2026-09-17 02:24:25.84715+07
9	auth	0007_alter_validators_add_error_messages	2026-09-17 02:24:25.851891+07
10	auth	0008_alter_user_username_max_length	2026-09-17 02:24:25.856725+07
11	auth	0009_alter_user_last_name_max_length	2026-09-17 02:24:25.861274+07
12	auth	0010_alter_group_name_max_length	2026-09-17 02:24:25.868982+07
13	auth	0011_update_proxy_permissions	2026-09-17 02:24:25.875209+07
14	auth	0012_alter_user_first_name_max_length	2026-09-17 02:24:25.881625+07
15	accounts	0001_initial	2026-09-17 02:24:25.945516+07
16	admin	0001_initial	2026-09-17 02:24:25.981329+07
17	admin	0002_logentry_remove_auto_add	2026-09-17 02:24:25.98859+07
18	admin	0003_logentry_add_action_flag_choices	2026-09-17 02:24:25.99551+07
19	berita	0001_initial	2026-09-17 02:24:26.019413+07
20	komunitas	0001_initial	2026-09-17 02:24:26.070741+07
21	sessions	0001_initial	2026-09-17 02:24:26.086428+07
22	timeline	0001_initial	2026-09-17 02:24:26.097761+07
23	translator	0001_initial	2026-09-17 02:24:26.123908+07
24	video	0001_initial	2026-09-17 02:24:26.136376+07
25	berita	0002_berita_author_name_berita_ringkasan_and_more	2026-09-17 03:25:15.140394+07
26	komunitas	0002_komunitas_alter_komunitastestimonial_options_and_more	2026-09-17 03:25:15.21905+07
27	timeline	0002_alter_timeline_options_timeline_created_at_and_more	2026-09-17 03:25:15.251685+07
28	video	0002_video_deskripsi_gerakan_video_gesture_pattern_and_more	2026-09-17 03:25:15.276523+07
\.


--
-- TOC entry 5192 (class 0 OID 33658)
-- Dependencies: 240
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- TOC entry 5189 (class 0 OID 33596)
-- Dependencies: 237
-- Data for Name: komunitas_activities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.komunitas_activities (id, judul, deskripsi, tipe, tanggal_mulai, tanggal_selesai, lokasi, gambar, is_active, created_at, updated_at) FROM stdin;
6d617bd3-f99f-4110-b3ec-f1d393817b13	Workshop Bahasa Isyarat Dasar	Belajar BISINDO bersama teman tuli.	workshop	\N	\N	Surabaya		t	2026-09-17 02:27:14.295063+07	2026-09-17 02:27:14.295081+07
\.


--
-- TOC entry 5196 (class 0 OID 41598)
-- Dependencies: 244
-- Data for Name: komunitas_direktori; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.komunitas_direktori (id, nama, deskripsi, deskripsi_lengkap, kategori, platform, link, logo, logo_url, anggota, status, kontak, email_kontak, created_at, updated_at) FROM stdin;
198e6df9-1993-41cc-bcbd-091d70b511b1	Gerkatin (Gerakan untuk Kesejahteraan Tunarungu Indonesia)	Organisasi nasional yang memperjuangkan hak dan kesejahteraan komunitas Tuli di Indonesia.	Gerkatin adalah organisasi nirlaba nasional yang telah berdiri sejak 1981 dan menjadi wadah utama bagi komunitas Tuli Indonesia. Gerkatin aktif dalam advokasi hak-hak penyandang disabilitas pendengaran, penyelenggaraan pelatihan bahasa isyarat, serta pemberdayaan ekonomi dan sosial anggota komunitas Tuli di seluruh provinsi.	Organisasi Tuli	Website	https://gerkatin.or.id		https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&w=200&q=80	5.000+ Anggota	approved	Sekretariat Gerkatin	info@gerkatin.or.id	2026-09-17 03:26:37.106578+07	2026-09-17 03:26:37.106588+07
04e4ee4f-5f3d-480c-b21f-0bee5fc2f585	Sign Language Indonesia Community	Komunitas belajar bahasa isyarat BISINDO & SIBI untuk masyarakat umum via WhatsApp Group.	Sign Language Indonesia Community adalah grup WhatsApp yang didirikan oleh para relawan dan fasilitator Tuli untuk memperkenalkan bahasa isyarat kepada masyarakat umum. Di sini, anggota bisa belajar kosa kata isyarat harian, berlatih melalui video challenge mingguan, dan berdiskusi seputar budaya Tuli Indonesia.	Belajar Isyarat	WhatsApp	https://chat.whatsapp.com/example-slic		https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=200&q=80	1.200+ Anggota	approved	Rina Mulyani	rina.slic@gmail.com	2026-09-17 03:26:37.110162+07	2026-09-17 03:26:37.110173+07
3eda17b0-f9e1-4f0b-b707-33e70eb950fc	Deaf Tech Indonesia	Forum teknologi & inovasi aksesibilitas untuk komunitas Tuli di platform Telegram.	Deaf Tech Indonesia adalah komunitas Telegram yang mempertemukan developer, desainer, dan inovator yang peduli pada aksesibilitas digital untuk Tuli. Topik diskusi mencakup AI untuk penerjemahan isyarat, UX aksesibel, captioning otomatis, dan peluang karir teknologi bagi penyandang disabilitas pendengaran.	Teknologi & Inovasi	Telegram	https://t.me/deaftechid		https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=200&q=80	850+ Anggota	approved	Ahmad Fauzi	ahmad@deaftech.id	2026-09-17 03:26:37.11218+07	2026-09-17 03:26:37.112189+07
2ca302e7-5eca-462a-9427-deeb7fffb753	Isyarat Nusantara	Channel Discord untuk diskusi dialek BISINDO dari berbagai daerah di Indonesia.	Isyarat Nusantara adalah server Discord yang menjadi ruang perkumpulan bagi penggiat bahasa isyarat dari berbagai provinsi di Indonesia. Server ini memiliki channel khusus untuk setiap dialek daerah (Jakarta, Yogyakarta, Bali, Padang, Makassar), serta channel tutorial video, sharing pengalaman, dan event virtual bulanan.	Komunitas Daerah	Discord	https://discord.gg/isyarat-nusantara		https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=200&q=80	600+ Anggota	approved	Dewi Lestari	dewi@isyaratnusantara.com	2026-09-17 03:26:37.114219+07	2026-09-17 03:26:37.114228+07
d8f56f9a-4b4b-4b54-9e7d-d0f3c4f36b42	Teman Tuli Bandung	Komunitas lokal Bandung yang aktif mengadakan kelas isyarat gratis dan sign cafe.	Teman Tuli Bandung adalah komunitas berbasis kota yang rutin mengadakan kelas bahasa isyarat gratis setiap akhir pekan, sign cafe bulanan, dan kampanye kesadaran inklusi di ruang publik. Dikelola oleh gabungan relawan dengar dan Tuli yang ingin menjembatani komunikasi di Kota Bandung.	Komunitas Lokal	Instagram	https://instagram.com/temantulibdg		https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=200&q=80	2.300+ Followers	approved	Bayu Pratama	temantulibdg@gmail.com	2026-09-17 03:26:37.116907+07	2026-09-17 03:26:37.116917+07
58300f5d-a7c2-4cc4-abee-b0d6fffbcc92	Komunitas Guru SLB Nusantara	Grup WhatsApp khusus guru SLB untuk berbagi materi dan metode pengajaran isyarat.	Komunitas Guru SLB Nusantara adalah wadah bagi para guru Sekolah Luar Biasa dari seluruh Indonesia untuk saling berbagi materi ajar, metode pengajaran bahasa isyarat, dan solusi tantangan pendidikan inklusif. Grup ini juga rutin mengadakan webinar dan diskusi tematik bersama pakar pendidikan khusus.	Pendidikan	WhatsApp	https://chat.whatsapp.com/example-guruslb		https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=200&q=80	450+ Guru	approved	Siti Rahmawati	siti.guruslb@gmail.com	2026-09-17 03:26:37.119095+07	2026-09-17 03:26:37.119104+07
\.


--
-- TOC entry 5190 (class 0 OID 33611)
-- Dependencies: 238
-- Data for Name: komunitas_members; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.komunitas_members (id, alasan_bergabung, status, approved_at, created_at, updated_at, approved_by_id, user_id) FROM stdin;
6e0900ea-1178-40cc-8119-cfb1f63b312a	Ingin memperdalam kemampuan bahasa isyarat dan berkontribusi.	approved	2026-09-17 02:27:14.321918+07	2026-09-17 02:27:14.307899+07	2026-09-17 02:27:14.322041+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	ee47d50e-befe-463b-bed4-22676bfe164d
\.


--
-- TOC entry 5191 (class 0 OID 33626)
-- Dependencies: 239
-- Data for Name: komunitas_testimonials; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.komunitas_testimonials (id, nama, peran, avatar, konten, rating, is_active, created_at, updated_at, user_id, avatar_url) FROM stdin;
803511b0-4521-4682-af81-b3d44de31ee5	Budi Santoso	Anggota Komunitas		SETARA sangat membantu saya berkomunikasi dengan teman-teman tuli!	5	t	2026-09-17 02:27:14.329094+07	2026-09-17 02:27:14.329112+07	ee47d50e-befe-463b-bed4-22676bfe164d	
4962f4e5-104b-4e75-9c09-e96707e2ec00	Andi Pratama	Relawan Teman Dengar		Platform SETARA sangat intuitif! Saya bisa belajar BISINDO sekaligus menguji pemahaman saya langsung dengan kamera real-time.	5	t	2026-09-17 03:26:37.126831+07	2026-09-17 03:26:37.126846+07	\N	https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80
76e4983b-ef62-467e-b95b-107d5bdede30	Rina Mulyani	Anggota Komunitas Tuli		Akhirnya ada platform yang menghargai keberadaan BISINDO sebagai bahasa alami kami, bukan sekadar memaksakan SIBI formal.	5	t	2026-09-17 03:26:37.130421+07	2026-09-17 03:26:37.130436+07	\N	https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80
c18e1465-020a-433a-951c-e803fb2bfa4e	Budi Santoso, S.Pd.	Guru SLB Negeri		Sangat membantu dalam mengajar murid-murid baru di kelas. Kamus visualnya lengkap dan responsif di berbagai perangkat.	5	t	2026-09-17 03:26:37.132728+07	2026-09-17 03:26:37.132738+07	\N	https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80
8d347b53-ebb7-4e14-9998-b02ebbae1dd8	Dewi Saraswati	Mahasiswa Ilmu Komunikasi		Fitur perbandingan SIBI vs BISINDO membuka wawasan saya mengenai linguistik isyarat Nusantara. Keren sekali!	5	t	2026-09-17 03:26:37.135164+07	2026-09-17 03:26:37.135176+07	\N	https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80
\.


--
-- TOC entry 5193 (class 0 OID 33670)
-- Dependencies: 241
-- Data for Name: timelines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.timelines (id, judul, deskripsi, tanggal, gambar, urutan, is_active, created_at, gambar_url, icon, kategori, tahun) FROM stdin;
2f6f9787-8fe5-474d-8528-7a6d1e265cfa	Awal Mula Perkembangan BISINDO	Komunitas Tuli di Indonesia mulai mengorganisir bahasa isyarat alami.	2010-01-01		1	t	2026-09-17 03:25:15.223962+07		Sparkles	Pencapaian	
890d581a-64fa-47ea-ac5e-bd4c822b9bd0	Lahirnya Gagasan SETARA	Riset awal kolaborasi antara mahasiswa teknik informatika dan komunitas Tuli untuk mengidentifikasi tantangan komunikasi dua arah.	Maret 2024		1	t	2026-09-17 03:26:37.090457+07		Sparkles	Pondasi	2024
8935adfe-1d56-4a87-8b68-e6cbce98e7f9	Rilis Prototipe Kamus SIBI v1.0	Peluncuran kamus digital 200 kata pertama dengan rekaman video peragaan isyarat resolusi tinggi.	Oktober 2024		2	t	2026-09-17 03:26:37.094714+07		BookOpen	Pengembangan	2024
17ce37f0-29fd-4f30-879e-5c2f6d6876f2	Integrasi Bahasa Alami BISINDO	Kolaborasi bersama fasilitator Tuli daerah untuk merekam variasi leksikal BISINDO dan ekspresi visual.	Juni 2025		3	t	2026-09-17 03:26:37.09758+07		Users	Ekspansi	2025
28dcee1c-abd1-40f2-8ad9-60c21c9e7b16	Implementasi AI YOLO 11 & Computer Vision	Penerapan pipeline deteksi 21 keypoints tangan secara real-time melalui kamera perangkat tanpa latensi.	Januari 2026		4	t	2026-09-17 03:26:37.099789+07		Cpu	Inovasi AI	2026
a12bd603-b769-432c-8f67-0234ba5213fc	Peluncuran SETARA v2.0 Terpadu	Platform terintegrasi dengan penerjemah dua arah (Text-to-Sign & Sign-to-Text), ruang edukasi, dan portal komunitas nasional.	Agustus 2026		5	t	2026-09-17 03:26:37.101762+07		Rocket	Milestone Utama	2026
\.


--
-- TOC entry 5194 (class 0 OID 33684)
-- Dependencies: 242
-- Data for Name: translation_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.translation_history (id, tipe_translasi, tipe_bahasa, input_text, output_text, video_ids, confidence_score, created_at, user_id) FROM stdin;
0a4346e7-e7b9-40e2-b7a2-9f4087fae0a1	text_to_sign	BISINDO	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-19 17:15:27.144507+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
4ce8085b-e570-496f-8907-68427e62adae	text_to_sign	BISINDO	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-19 17:15:27.16198+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
ed2b950b-e0e5-4d2f-81d2-fdcce6942197	text_to_sign	SIBI	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-20 17:06:10.019484+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
afe5cc59-fa96-4087-a66c-20af4edde800	text_to_sign	SIBI	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-20 17:06:10.045089+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
a3a45e92-9584-4780-a414-ea2c518f564f	text_to_sign	SIBI	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-20 17:07:30.904914+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
efca0834-263c-4192-9d90-169cc6992535	text_to_sign	SIBI	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-20 17:07:30.930142+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
26981fa9-d0c4-4fdf-a0cc-ade5d923ee90	text_to_sign	SIBI	maaf	maaf	[""]	0	2026-09-20 17:07:46.985385+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
d56ac400-158b-4873-bf1c-219a0348cbbb	text_to_sign	SIBI	MAAF	maaf	[""]	0	2026-09-20 17:08:06.179963+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
9ab3f744-c523-4c30-98f0-1dd95d48c3f2	text_to_sign	BISINDO	MAAF	maaf	[""]	0	2026-09-20 17:15:35.437915+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
5e9db6fc-0e85-41e7-a8c2-bc2ca55b854a	text_to_sign	BISINDO	MAAF	maaf	[""]	0	2026-09-20 17:15:45.800157+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
a3f18ddc-acdd-4fee-9a4c-40da181a0718	text_to_sign	BISINDO	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-20 17:16:13.493805+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
9cb080d5-1c00-4cd9-ae1e-47d3941f51df	text_to_sign	BISINDO	aku sayang ibu	aku, sayang, ibu	["", "", ""]	0	2026-09-20 17:16:13.528211+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
dcf24def-3e51-4a14-8d91-b5b4c5b7989b	text_to_sign	BISINDO	maaf	maaf	[""]	0	2026-09-20 17:16:25.949848+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
23cd2899-a6c9-41a3-ba64-d31dc9bcd490	text_to_sign	BISINDO	saya	saya	[""]	0	2026-09-20 17:31:43.035156+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
873d7273-c477-45a1-a498-72d305642e2b	text_to_sign	BISINDO	saya	saya	[""]	0	2026-09-20 17:31:47.529316+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
585f6a57-a2d9-4c4b-94c2-0331f46a3a78	text_to_sign	BISINDO	saya	saya	[""]	0	2026-09-20 17:31:48.690715+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
4dbafddc-11f0-4bdd-a7b3-875309e91269	text_to_sign	BISINDO	aku	aku	[""]	0	2026-09-20 17:32:07.133168+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
dce2c76b-7c58-465b-afb2-830d35413481	text_to_sign	BISINDO	aku	aku	[""]	0	2026-09-20 17:32:14.082145+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
b24a2f42-1794-4dd9-b4ed-9cc115b8d8e7	text_to_sign	BISINDO	aku maaf	aku, maaf	["", ""]	0	2026-09-20 17:33:01.316302+07	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3
\.


--
-- TOC entry 5181 (class 0 OID 33474)
-- Dependencies: 229
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (password, last_login, is_superuser, id, email, full_name, avatar, role, is_staff, is_active, bio, is_komunitas_member, joined_komunitas_at, date_joined) FROM stdin;
pbkdf2_sha256$1500000$MLlv3KdV2rqQF4AtW80FTf$KNkQjIMIidcGlebLIlwIJ/Q5OQJFUdzAHyWT3YNuVsY=	\N	f	e0812b93-8a2e-49fd-b742-e318e54ca27c	user@setara.id	Budi Santoso		user	f	t		f	\N	2026-09-17 02:26:00.051802+07
pbkdf2_sha256$1500000$NUuTOqzWRlzHhYLtW4mKvn$oniSffYOC+fAXE3tQXbQIkB9RRX2XFxkGojvUC8gSdw=	\N	f	ee47d50e-befe-463b-bed4-22676bfe164d	user2@setara.id	Budi Santoso		user	f	t		t	2026-09-17 02:27:14.321918+07	2026-09-17 02:27:12.841277+07
pbkdf2_sha256$1500000$OvZzSIGhVLx1KtPHHRoxri$e2Z9FqHbj3+G+E1sRTfZVphmQG0T4XYIq6EICZMj5Q0=	\N	t	505c9fd8-f6a9-4615-9c87-1e7d5c05c8c3	admin@setara.id	Admin SETARA		admin	t	t		f	\N	2026-09-17 02:24:48.004805+07
\.


--
-- TOC entry 5183 (class 0 OID 33495)
-- Dependencies: 231
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5185 (class 0 OID 33504)
-- Dependencies: 233
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5195 (class 0 OID 33705)
-- Dependencies: 243
-- Data for Name: videos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.videos (id, kata, video_file, thumbnail, tipe_bahasa, tag, durasi, status, created_at, deskripsi_gerakan, gesture_pattern, kategori, thumbnail_url, video_url) FROM stdin;
facb0763-6f5d-431d-baea-9d9437a4d88b	selamat			SIBI	sapaan	0	active	2026-09-17 02:27:14.260113+07		hand_wave_forehead	Umum		
d887cbe6-c23c-48a8-9eba-866688075d4b	halo			BISINDO		2	active	2026-09-17 03:26:37.144403+07	Tangan terbuka di samping pelipis/dahi, lalu digerakkan melambai ke arah luar secara ramah.	hand_wave_forehead	Sapaan		
650163d6-bf97-47d4-ab13-1461a3c71743	kamu			BISINDO		2	active	2026-09-17 03:26:37.149893+07	Jari telunjuk tangan dominan menunjuk lurus ke arah lawan bicara secara sopan.	point_forward	Kata Ganti		
586a8832-1791-41e0-824a-69e882703282	terima kasih			BISINDO		2	active	2026-09-17 03:26:37.15249+07	Ujung jari tangan terbuka menyentuh dagu/bibir bawah, lalu digerakkan mendatar ke depan.	chin_to_front	Kesopanan		
38da8130-4299-45be-a999-2c998b55726c	tolong			BISINDO		2	active	2026-09-17 03:26:37.159201+07	Kedua telapak tangan dirapatkan di depan dada seperti memohon dengan sedikit anggukan kepala.	palms_together_chest	Kesopanan		
204d7d3b-99e9-4c8a-9342-db4e18bb6ac8	selamat			BISINDO		2	active	2026-09-17 03:26:37.161332+07	Kedua ibu jari teracung di depan dada lalu digerakkan naik ke atas secara mantap.	thumbs_up_chest	Sapaan		
ea2ed39f-f736-48b9-aa54-04da4a1a65af	pagi			BISINDO		2	active	2026-09-17 03:26:37.164079+07	Satu tangan membentuk lingkaran matahari yang bergerak naik dari balik lengan horizontal lainnya.	sun_rise_horizon	Waktu		
1987709d-b525-41ef-ae75-ee180d655a3d	malam			BISINDO		2	active	2026-09-17 03:26:37.169731+07	Tangan bergerak melengkung ke bawah meniru matahari yang terbenam di balik ufuk.	sun_set_down	Waktu		
b5363115-e3d8-4e95-ab97-39138149bc6a	belajar			BISINDO		2	active	2026-09-17 03:26:37.172931+07	Ujung jari menyentuh telapak tangan kiri lalu diangkat menyentuh dahi (mengambil ilmu).	palm_to_forehead	Aktivitas		
92253714-2c64-48e6-8476-7a3be0d16f77	isyarat			BISINDO		2	active	2026-09-17 03:26:37.175361+07	Kedua telunjuk berputar bergantian di depan dada melambangkan komunikasi visual dinamis.	rotating_index_fingers	Komunikasi		
6062ae4d-f603-492d-a613-48e484058afc	bahasa			BISINDO		2	active	2026-09-17 03:26:37.177382+07	Kedua tangan membentuk abjad B lalu digerakkan bergelombang ke samping luar.	b_hands_wave	Komunikasi		
26b023e9-b6d0-4ac7-b6d9-fb5a1975ee3b	semangat			BISINDO		2	active	2026-09-17 03:26:37.184787+07	Kedua tangan mengepal kuat di samping pinggang lalu dihentakkan naik ke atas secara bertenaga.	fists_pump_up	Emosi		
fed5177e-183f-4179-b3a4-2eecdcf431b8	tuli			BISINDO		2	active	2026-09-17 03:26:37.187643+07	Jari telunjuk menyentuh daun telinga lalu berpindah menyentuh bibir (identitas budaya Tuli).	ear_to_mouth_touch	Identitas		
571bd19e-703a-4e97-91c2-94fda2b6abca	dengar			BISINDO		2	active	2026-09-17 03:26:37.189658+07	Tangan sedikit melengkung di belakang telinga mengindikasikan kemampuan mendengar.	cup_ear	Identitas		
963594b4-d579-420d-b227-b98848b793da	teman			BISINDO		2	active	2026-09-17 03:26:37.191679+07	Kedua jari telunjuk saling mengait satu sama lain melambangkan persahabatan erat.	hook_index_fingers	Sosial		
3b3b6fb9-f056-4257-976a-e312b23f8d23	keluarga			BISINDO		2	active	2026-09-17 03:26:37.194303+07	Kedua tangan membentuk huruf F/lingkaran lalu bergerak melingkar hingga kelingking bersentuhan.	circle_touch_pinkies	Sosial		
2de2f3e5-9d67-47df-999d-8edd3c21f297	sekolah			BISINDO		2	active	2026-09-17 03:26:37.196503+07	Telapak tangan kanan menepuk telapak tangan kiri dua kali secara mendatar.	clap_palms_horizontal	Pendidikan		
440bc3e4-1fd3-4b6e-91dc-3e001d6952f2	rumah			BISINDO		2	active	2026-09-17 03:26:37.198773+07	Ujung jari kedua tangan dipertemukan membentuk segitiga atap rumah di depan dada.	roof_shape_hands	Umum		
9dd8e99f-d741-4a54-923c-bd4ee3058172	makan			BISINDO		2	active	2026-09-17 03:26:37.201747+07	Ujung-ujung jari terkumpul menyentuh bibir dua kali menirukan gerakan menyuap makanan.	fingertips_to_mouth	Kebutuhan		
9c431c46-002e-43c3-b947-fbba683be62a	minum			BISINDO		2	active	2026-09-17 03:26:37.203805+07	Tangan membentuk huruf C seperti memegang cangkir lalu diangkat ke arah mulut.	c_cup_to_mouth	Kebutuhan		
056e002f-65b0-4471-8dbc-b201450760b6	sayang			BISINDO	cinta,sayang,kasih	2	active	2026-09-19 16:52:10.081021+07	Kedua telapak tangan menyilang di atas dada membentuk pelukan hangat penuh kasih sayang.	cross_chest_hug	Perasaan		
b866f95d-098f-4344-9178-934aa433f7cc	ibu			BISINDO	ibu,mama,bunda	2	active	2026-09-19 16:52:10.09184+07	Ibu jari tangan kanan menyentuh dagu atau pipi bawah melambangkan sosok ibu yang lembut.	thumb_chin	Keluarga		
b7d1fa61-69c6-4068-afbc-ffcca03c8ffa	ayah			BISINDO	ayah,bapak,papa	2	active	2026-09-19 16:52:10.094787+07	Ibu jari tangan kanan menyentuh bagian dahi atas melambangkan figur ayah yang bijaksana.	thumb_forehead	Keluarga		
8598e959-8036-4079-b456-9a5e24a8531c	cinta			BISINDO	cinta,love,sayang	2	active	2026-09-19 16:52:10.096935+07	Tangan membentuk simbol cinta dan menyilangkan tangan di dada dengan senyuman tulus.	cross_chest_hug	Perasaan		
d831783f-f618-46e5-a8b1-8f32bea29343	setara			BISINDO	setara,inklusif,adil	2	active	2026-09-19 16:52:10.099227+07	Kedua telapak tangan mendatar sejajar di depan dada melambangkan kesetaraan, keadilan, dan inklusivitas.	equal_parallel_hands	Nilai & Visi		
001a3732-abc7-46f1-8192-3585687ee575	saya			BISINDO	saya,aku,kami	1	active	2026-09-19 16:52:10.102041+07	Telapak tangan kanan terbuka menempel di dada bagian tengah secara sopan dan santun.	palm_chest	Kata Ganti		
fd352862-2a4e-4d8b-8ffc-c3d5481ca180	dia			BISINDO	dia,beliau,mereka	1	active	2026-09-19 16:52:10.104391+07	Jari telunjuk mengarah ke samping mengindikasikan orang ketiga.	point_side	Kata Ganti		
2913a07b-eae9-43c6-97ec-6059df9bd2a0	bantu			BISINDO	bantu,tolong,dukung	2	active	2026-09-19 16:52:10.106379+07	Satu tangan menopang tangan lain yang terkepal dan digerakkan ke atas melambangkan gotong royong.	support_motion	Kata Kerja		
4d57c8b4-cff9-4b85-9b87-31f85eb31e8e	kasih			BISINDO	kasih,beri,peduli	1	active	2026-09-19 16:52:10.109104+07	Tangan bergerak dari arah dada keluar ke depan melambangkan pemberian dan kepedulian.	give_motion	Ungkapan		
fe3abd2e-d40d-48f4-9840-7d6132813495	terima			BISINDO	terima,sambung,dapat	1	active	2026-09-19 16:52:10.111207+07	Kedua tangan terbuka bergerak dari depan mendekat ke arah dada melambangkan penerimaan yang tulus.	receive_motion	Ungkapan		
64e1fae1-47e0-4543-bde2-75f416b1ca58	sama-sama			BISINDO	sama-sama,kembali	2	active	2026-09-17 03:26:37.154863+07	Kedua tangan terbuka di depan dada digerakkan ke depan bawah secara bersamaan.	two_hands_chest_out	Sapaan / Kesopanan		
c14a78e9-6a37-46f1-b8b7-1102f7b97d20	sehat			BISINDO	sehat,bugar,kuat	2	active	2026-09-17 03:26:37.206214+07	Kedua tangan terbuka di dada digerakkan ke atas dengan senyum bugar.	hands_chest_up	Kesehatan		
9e1fe3d4-2c63-4610-ae56-4c7d7694a544	senang			BISINDO	senang,bahagia,gembira	2	active	2026-09-17 03:26:37.182323+07	Telapak tangan mengusap dada ke arah atas berulang dengan ekspresi wajah gembira.	chest_brush_up	Perasaan		
ecbf32a5-ac0c-466e-b49d-1c570fb7db99	indonesia			BISINDO	indonesia,merah putih,nusantara	2	active	2026-09-17 03:26:37.180095+07	Tangan kanan melambai horizontal dari kiri ke kanan di depan dada menyerupai kibaran bendera merah putih.	flag_wave_motion	Kebangsaan		
033db0a5-5b6b-46da-8354-85b8313d487e	siang			BISINDO	siang,terik	1	active	2026-09-17 03:26:37.167221+07	Lengan kanan tegak lurus mengarah ke atas tepat di atas kepala melambangkan matahari di puncak.	sun_overhead	Waktu		
f273c5a2-bbec-4ec6-a0bc-f767f217d131	maaf	video/isyarat/maaf_f273c5a2.mp4		BISINDO		2	active	2026-09-20 17:07:08.409709+07		hand_wave_forehead	Ungkapan		/media/video/isyarat/maaf_f273c5a2.mp4
a43627a1-9e6f-4d7b-a322-a0d1c270ecdb	aku	video/isyarat/aku_a43627a1.mp4		BISINDO		2	active	2026-09-17 03:26:37.147525+07	Jari telunjuk tangan dominan menunjuk ke arah dada diri sendiri.	point_chest	Kata Ganti		/media/video/isyarat/aku_a43627a1.mp4
\.


--
-- TOC entry 5202 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5203 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5204 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- TOC entry 5205 (class 0 OID 0)
-- Dependencies: 234
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5206 (class 0 OID 0)
-- Dependencies: 221
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- TOC entry 5207 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 28, true);


--
-- TOC entry 5208 (class 0 OID 0)
-- Dependencies: 230
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- TOC entry 5209 (class 0 OID 0)
-- Dependencies: 232
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- TOC entry 4948 (class 2606 OID 33471)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4953 (class 2606 OID 33456)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4956 (class 2606 OID 33445)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 33434)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4943 (class 2606 OID 33447)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4945 (class 2606 OID 33426)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4980 (class 2606 OID 33586)
-- Name: berita berita_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.berita
    ADD CONSTRAINT berita_pkey PRIMARY KEY (id);


--
-- TOC entry 4983 (class 2606 OID 33588)
-- Name: berita berita_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.berita
    ADD CONSTRAINT berita_slug_key UNIQUE (slug);


--
-- TOC entry 4976 (class 2606 OID 33555)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4938 (class 2606 OID 33416)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4940 (class 2606 OID 33414)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 33404)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4996 (class 2606 OID 33667)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4985 (class 2606 OID 33610)
-- Name: komunitas_activities komunitas_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_activities
    ADD CONSTRAINT komunitas_activities_pkey PRIMARY KEY (id);


--
-- TOC entry 5009 (class 2606 OID 41618)
-- Name: komunitas_direktori komunitas_direktori_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_direktori
    ADD CONSTRAINT komunitas_direktori_pkey PRIMARY KEY (id);


--
-- TOC entry 4988 (class 2606 OID 33623)
-- Name: komunitas_members komunitas_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_members
    ADD CONSTRAINT komunitas_members_pkey PRIMARY KEY (id);


--
-- TOC entry 4990 (class 2606 OID 33625)
-- Name: komunitas_members komunitas_members_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_members
    ADD CONSTRAINT komunitas_members_user_id_key UNIQUE (user_id);


--
-- TOC entry 4992 (class 2606 OID 33640)
-- Name: komunitas_testimonials komunitas_testimonials_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_testimonials
    ADD CONSTRAINT komunitas_testimonials_pkey PRIMARY KEY (id);


--
-- TOC entry 4999 (class 2606 OID 33683)
-- Name: timelines timelines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.timelines
    ADD CONSTRAINT timelines_pkey PRIMARY KEY (id);


--
-- TOC entry 5001 (class 2606 OID 33698)
-- Name: translation_history translation_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_history
    ADD CONSTRAINT translation_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4959 (class 2606 OID 33493)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4964 (class 2606 OID 33502)
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 33514)
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4961 (class 2606 OID 33491)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 33511)
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4973 (class 2606 OID 33528)
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5007 (class 2606 OID 33717)
-- Name: videos videos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (id);


--
-- TOC entry 4946 (class 1259 OID 33472)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4951 (class 1259 OID 33467)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4954 (class 1259 OID 33468)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4941 (class 1259 OID 33453)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4978 (class 1259 OID 33595)
-- Name: berita_author_id_2581dab3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX berita_author_id_2581dab3 ON public.berita USING btree (author_id);


--
-- TOC entry 4981 (class 1259 OID 33594)
-- Name: berita_slug_142a43a8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX berita_slug_142a43a8_like ON public.berita USING btree (slug varchar_pattern_ops);


--
-- TOC entry 4974 (class 1259 OID 33566)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4977 (class 1259 OID 33567)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4994 (class 1259 OID 33669)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4997 (class 1259 OID 33668)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4986 (class 1259 OID 33651)
-- Name: komunitas_members_approved_by_id_c38f0213; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX komunitas_members_approved_by_id_c38f0213 ON public.komunitas_members USING btree (approved_by_id);


--
-- TOC entry 4993 (class 1259 OID 33657)
-- Name: komunitas_testimonials_user_id_05f1708c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX komunitas_testimonials_user_id_05f1708c ON public.komunitas_testimonials USING btree (user_id);


--
-- TOC entry 5002 (class 1259 OID 33704)
-- Name: translation_history_user_id_3fbf2066; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX translation_history_user_id_3fbf2066 ON public.translation_history USING btree (user_id);


--
-- TOC entry 4957 (class 1259 OID 33512)
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);


--
-- TOC entry 4962 (class 1259 OID 33526)
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- TOC entry 4965 (class 1259 OID 33525)
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- TOC entry 4968 (class 1259 OID 33540)
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- TOC entry 4971 (class 1259 OID 33539)
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- TOC entry 5003 (class 1259 OID 33720)
-- Name: videos_kata_126a3f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX videos_kata_126a3f_idx ON public.videos USING btree (kata, tipe_bahasa);


--
-- TOC entry 5004 (class 1259 OID 33718)
-- Name: videos_kata_9fd1a206; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX videos_kata_9fd1a206 ON public.videos USING btree (kata);


--
-- TOC entry 5005 (class 1259 OID 33719)
-- Name: videos_kata_9fd1a206_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX videos_kata_9fd1a206_like ON public.videos USING btree (kata varchar_pattern_ops);


--
-- TOC entry 5011 (class 2606 OID 33462)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5012 (class 2606 OID 33457)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5010 (class 2606 OID 33448)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5019 (class 2606 OID 41592)
-- Name: berita berita_author_id_2581dab3_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.berita
    ADD CONSTRAINT berita_author_id_2581dab3_fk_users_id FOREIGN KEY (author_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5017 (class 2606 OID 33556)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5018 (class 2606 OID 33561)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5020 (class 2606 OID 33641)
-- Name: komunitas_members komunitas_members_approved_by_id_c38f0213_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_members
    ADD CONSTRAINT komunitas_members_approved_by_id_c38f0213_fk_users_id FOREIGN KEY (approved_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5021 (class 2606 OID 33646)
-- Name: komunitas_members komunitas_members_user_id_a64246f8_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_members
    ADD CONSTRAINT komunitas_members_user_id_a64246f8_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5022 (class 2606 OID 33652)
-- Name: komunitas_testimonials komunitas_testimonials_user_id_05f1708c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.komunitas_testimonials
    ADD CONSTRAINT komunitas_testimonials_user_id_05f1708c_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5023 (class 2606 OID 33699)
-- Name: translation_history translation_history_user_id_3fbf2066_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translation_history
    ADD CONSTRAINT translation_history_user_id_3fbf2066_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5013 (class 2606 OID 33520)
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5014 (class 2606 OID 33515)
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5015 (class 2606 OID 33534)
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5016 (class 2606 OID 33529)
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-09-20 19:30:12

--
-- PostgreSQL database dump complete
--

\unrestrict Y7URCDMo7pb9wjCZ1SK5HutmLY2qivaOL8ThNfJTOtjHhHdcjzEm9FmWMjyjAnA

