# Generated by Django 6.1.1 on 2026-09-16 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('konten', models.TextField(help_text='Isi berita (rich text)')),
                ('kategori', models.CharField(choices=[('edukasi', 'Edukasi'), ('komunitas', 'Komunitas'), ('teknologi', 'Teknologi'), ('event', 'Event')], default='edukasi', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berita_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'db_table': 'berita',
                'ordering': ['-created_at'],
            },
        ),
    ]
