# Generated by Django 6.1.1 on 2026-09-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='author_name',
            field=models.CharField(blank=True, default='Tim Redaksi SETARA', max_length=255),
        ),
        migrations.AddField(
            model_name='berita',
            name='ringkasan',
            field=models.TextField(blank=True, default='', help_text='Ringkasan singkat berita'),
        ),
        migrations.AddField(
            model_name='berita',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='berita',
            name='waktu_baca',
            field=models.CharField(blank=True, default='4 menit', max_length=50),
        ),
        migrations.AlterField(
            model_name='berita',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berita_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='berita',
            name='kategori',
            field=models.CharField(default='Edukasi', max_length=50),
        ),
        migrations.AlterField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
